language: "zh"

pipeline:
- name: "nlp_mitie"
  model: "nlu/data/total_word_feature_extractor_zh.dat"
- name: "tokenizer_jieba"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"


#Mitie Nlp 初始化mitie结构
#.dat 语言模型文件
#tokenizer_jieba为中文创建标签
#mitie的相关配置